# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:"1758416930859427"  2cfb46261ed92897daf78df55a4b2de7
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
production:
    facebook_api_id: '135964403706519'
    facebook_api_secret: c05188e0a79f2921416f98c0032ac773

development:
    facebook_api_id: '135964403706519'
    facebook_api_secret: c05188e0a79f2921416f98c0032ac773
    facebookk_api_id: '1534369286628180'
    facebookk_api_secret: ecae8bd065dbb831a0dc5bc3f034251e
    google_api_id: 1065906643349-fd4043gfbdfs0u5fj68rggi6oo35guec.apps.googleusercontent.com
    google_api_secret: DgkHvQiLmoFitoDD7IpVj0EM
    linkedin_api_id: 78zm0obikz2oia
    linkedin_api_secret: nfS6Ib6bZYJ2BKs5
