default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  username: rails_dev
  password: olatunbosun
  host: localhost
  port: 5432


development:
  <<: *default
  database: gradnet_development

test:
  <<: *default
  database: gradnet_test
